rm ./http:__challonge.com_heatwave10.p
rm ./http:__challonge.com_heatwave11.p
rm ./http:__challonge.com_heatwave12.p
rm ./http:__challonge.com_heatwave13.p
rm ./http:__challonge.com_heatwave14.p
rm ./http:__challonge.com_heatwave15.p
rm ./http:__challonge.com_heatwave16.p
rm ./http:__challonge.com_heatwave17.p
rm ./http:__challonge.com_heatwave18.p
rm ./http:__challonge.com_heatwave19.p
rm ./http:__challonge.com_heatwave2.p
rm ./http:__challonge.com_heatwave20.p
rm ./http:__challonge.com_heatwave21.p
rm ./http:__challonge.com_heatwave22.p
rm ./http:__challonge.com_heatwave23.p
rm ./http:__challonge.com_heatwave24.p
rm ./http:__challonge.com_heatwave25.p
rm ./http:__challonge.com_heatwave26.p
rm ./http:__challonge.com_heatwave27.p
rm ./http:__challonge.com_heatwave28.p
rm ./http:__challonge.com_heatwave29.p
rm ./http:__challonge.com_heatwave3.p
rm ./http:__challonge.com_heatwave30.p
rm ./http:__challonge.com_heatwave31.p
rm ./http:__challonge.com_heatwave32.p
rm ./http:__challonge.com_heatwave34.p
rm ./http:__challonge.com_heatwave35.p
rm ./http:__challonge.com_heatwave36.p
rm ./http:__challonge.com_heatwave37.p
rm ./http:__challonge.com_heatwave38.p
rm ./http:__challonge.com_heatwave39.p
rm ./http:__challonge.com_heatwave4.p
rm ./http:__challonge.com_heatwave40.p
rm ./http:__challonge.com_heatwave41.p
rm ./http:__challonge.com_heatwave42.p
rm ./http:__challonge.com_heatwave43.p
rm ./http:__challonge.com_heatwave44.p
rm ./http:__challonge.com_heatwave45.p
rm ./http:__challonge.com_heatwave46.p
rm ./http:__challonge.com_heatwave47.p
rm ./http:__challonge.com_heatwave48.p
rm ./http:__challonge.com_heatwave49.p
rm ./http:__challonge.com_heatwave5.p
rm ./http:__challonge.com_heatwave50.p
rm ./http:__challonge.com_heatwave51.p
rm ./http:__challonge.com_heatwave52.p
rm ./http:__challonge.com_heatwave53.p
rm ./http:__challonge.com_heatwave54.p
rm ./http:__challonge.com_heatwave55.p
rm ./http:__challonge.com_heatwave56.p
rm ./http:__challonge.com_heatwave57.p
rm ./http:__challonge.com_heatwave58.p
rm ./http:__challonge.com_heatwave59.p
rm ./http:__challonge.com_heatwave6.p
rm ./http:__challonge.com_heatwave60.p
rm ./http:__challonge.com_heatwave61.p
rm ./http:__challonge.com_heatwave62.p
rm ./http:__challonge.com_heatwave63.p
rm ./http:__challonge.com_heatwave64.p
rm ./http:__challonge.com_heatwave65.p
rm ./http:__challonge.com_heatwave66.p
rm ./http:__challonge.com_heatwave67.p
rm ./http:__challonge.com_heatwave68.p
rm ./http:__challonge.com_heatwave69.p
rm ./http:__challonge.com_heatwave7.p
rm ./http:__challonge.com_heatwave70.p
rm ./http:__challonge.com_heatwave71.p
rm ./http:__challonge.com_heatwave72.p
rm ./http:__challonge.com_heatwave73.p
rm ./http:__challonge.com_heatwave74.p
rm ./http:__challonge.com_heatwave75.p
rm ./http:__challonge.com_heatwave76.p
rm ./http:__challonge.com_heatwave77.p
rm ./http:__challonge.com_heatwave78.p
rm ./http:__challonge.com_heatwave79.p
rm ./http:__challonge.com_heatwave8.p
rm ./http:__challonge.com_heatwave80.p
rm ./http:__challonge.com_heatwave81.p
rm ./http:__challonge.com_heatwave82.p
rm ./http:__challonge.com_heatwave83.p
rm ./http:__challonge.com_heatwave84.p
rm ./http:__challonge.com_heatwave9.p
rm ./http:__smascho.challonge.com_FCWUA1.p
rm ./http:__smascho.challonge.com_FCWUA10.p
rm ./http:__smascho.challonge.com_FCWUA11.p
rm ./http:__smascho.challonge.com_FCWUA12.p
rm ./http:__smascho.challonge.com_FCWUA13.p
rm ./http:__smascho.challonge.com_FCWUA14.p
rm ./http:__smascho.challonge.com_FCWUA15.p
rm ./http:__smascho.challonge.com_FCWUA16.p
rm ./http:__smascho.challonge.com_FCWUA17.p
rm ./http:__smascho.challonge.com_FCWUA18.p
rm ./http:__smascho.challonge.com_FCWUA19.p
rm ./http:__smascho.challonge.com_FCWUA20.p
rm ./http:__smascho.challonge.com_FCWUA21.p
rm ./http:__smascho.challonge.com_FCWUA22.p
rm ./http:__smascho.challonge.com_FCWUA23.p
rm ./http:__smascho.challonge.com_FCWUA24.p
rm ./http:__smascho.challonge.com_FCWUA25.p
rm ./http:__smascho.challonge.com_FCWUA26.p
rm ./http:__smascho.challonge.com_FCWUA27.p
rm ./http:__smascho.challonge.com_FCWUA28.p
rm ./http:__smascho.challonge.com_FCWUA29.p
rm ./http:__smascho.challonge.com_FCWUA30.p
rm ./http:__smascho.challonge.com_FCWUA31.p
rm ./http:__smascho.challonge.com_FCWUA32.p
rm ./http:__smascho.challonge.com_FCWUA33.p
rm ./http:__smascho.challonge.com_FCWUA34.p
rm ./http:__smascho.challonge.com_FCWUA35.p
rm ./http:__smascho.challonge.com_FCWUA36.p
rm ./http:__smascho.challonge.com_FCWUA37.p
rm ./http:__smascho.challonge.com_FCWUA38.p
rm ./http:__smascho.challonge.com_FCWUA39.p
rm ./http:__smascho.challonge.com_FCWUA4.p
rm ./http:__smascho.challonge.com_FCWUA40.p
rm ./http:__smascho.challonge.com_FCWUA41.p
rm ./http:__smascho.challonge.com_FCWUA42.p
rm ./http:__smascho.challonge.com_FCWUA43.p
rm ./http:__smascho.challonge.com_FCWUA44.p
rm ./http:__smascho.challonge.com_FCWUA45.p
rm ./http:__smascho.challonge.com_FCWUA46.p
rm ./http:__smascho.challonge.com_FCWUA47.p
rm ./http:__smascho.challonge.com_FCWUA48.p
rm ./http:__smascho.challonge.com_FCWUA49.p
rm ./http:__smascho.challonge.com_FCWUA5.p
rm ./http:__smascho.challonge.com_FCWUA50.p
rm ./http:__smascho.challonge.com_FCWUA51.p
rm ./http:__smascho.challonge.com_FCWUA52.p
rm ./http:__smascho.challonge.com_FCWUA53.p
rm ./http:__smascho.challonge.com_FCWUA54.p
rm ./http:__smascho.challonge.com_FCWUA6.p
rm ./http:__smascho.challonge.com_FCWUA7.p
rm ./http:__smascho.challonge.com_FCWUA8.p
rm ./http:__smascho.challonge.com_FCWUA9.p
rm ./http:__smascho.challonge.com_FCWUIB1.p
rm ./http:__smascho.challonge.com_FCWUIB10.p
rm ./http:__smascho.challonge.com_FCWUIB11.p
rm ./http:__smascho.challonge.com_FCWUIB12.p
rm ./http:__smascho.challonge.com_FCWUIB13.p
rm ./http:__smascho.challonge.com_FCWUIB14.p
rm ./http:__smascho.challonge.com_FCWUIB15.p
rm ./http:__smascho.challonge.com_FCWUIB16.p
rm ./http:__smascho.challonge.com_FCWUIB17.p
rm ./http:__smascho.challonge.com_FCWUIB18.p
rm ./http:__smascho.challonge.com_FCWUIB19.p
rm ./http:__smascho.challonge.com_FCWUIB2.p
rm ./http:__smascho.challonge.com_FCWUIB20.p
rm ./http:__smascho.challonge.com_FCWUIB21.p
rm ./http:__smascho.challonge.com_FCWUIB22.p
rm ./http:__smascho.challonge.com_FCWUIB23.p
rm ./http:__smascho.challonge.com_FCWUIB24.p
rm ./http:__smascho.challonge.com_FCWUIB25.p
rm ./http:__smascho.challonge.com_FCWUIB26.p
rm ./http:__smascho.challonge.com_FCWUIB27.p
rm ./http:__smascho.challonge.com_FCWUIB28.p
rm ./http:__smascho.challonge.com_FCWUIB29.p
rm ./http:__smascho.challonge.com_FCWUIB30.p
rm ./http:__smascho.challonge.com_FCWUIB31.p
rm ./http:__smascho.challonge.com_FCWUIB32.p
rm ./http:__smascho.challonge.com_FCWUIB33.p
rm ./http:__smascho.challonge.com_FCWUIB34.p
rm ./http:__smascho.challonge.com_FCWUIB35.p
rm ./http:__smascho.challonge.com_FCWUIB36.p
rm ./http:__smascho.challonge.com_FCWUIB37.p
rm ./http:__smascho.challonge.com_FCWUIB38.p
rm ./http:__smascho.challonge.com_FCWUIB39.p
rm ./http:__smascho.challonge.com_FCWUIB4.p
rm ./http:__smascho.challonge.com_FCWUIB40.p
rm ./http:__smascho.challonge.com_FCWUIB41.p
rm ./http:__smascho.challonge.com_FCWUIB42.p
rm ./http:__smascho.challonge.com_FCWUIB43.p
rm ./http:__smascho.challonge.com_FCWUIB44.p
rm ./http:__smascho.challonge.com_FCWUIB45.p
rm ./http:__smascho.challonge.com_FCWUIB46.p
rm ./http:__smascho.challonge.com_FCWUIB47.p
rm ./http:__smascho.challonge.com_FCWUIB48.p
rm ./http:__smascho.challonge.com_FCWUIB49.p
rm ./http:__smascho.challonge.com_FCWUIB5.p
rm ./http:__smascho.challonge.com_FCWUIB50.p
rm ./http:__smascho.challonge.com_FCWUIB51.p
rm ./http:__smascho.challonge.com_FCWUIB52.p
rm ./http:__smascho.challonge.com_FCWUIB53.p
rm ./http:__smascho.challonge.com_FCWUIB54.p
rm ./http:__smascho.challonge.com_FCWUIB6.p
rm ./http:__smascho.challonge.com_FCWUIB7.p
rm ./http:__smascho.challonge.com_FCWUIB8.p
rm ./http:__smascho.challonge.com_FCWUIB9.p
rm ./http:__smashco.challonge.com_CSUWW100WUD.p
rm ./http:__smashco.challonge.com_CSUWW100WUS.p
rm ./http:__smashco.challonge.com_CSUWW101WUD.p
rm ./http:__smashco.challonge.com_CSUWW101WUS.p
rm ./http:__smashco.challonge.com_CSUWW102WUD.p
rm ./http:__smashco.challonge.com_CSUWW102WUS.p
rm ./http:__smashco.challonge.com_CSUWW103WUD.p
rm ./http:__smashco.challonge.com_CSUWW103WUS.p
rm ./http:__smashco.challonge.com_CSUWW104WUD.p
rm ./http:__smashco.challonge.com_CSUWW104WUS.p
rm ./http:__smashco.challonge.com_CSUWW105WUD.p
rm ./http:__smashco.challonge.com_CSUWW105WUS.p
rm ./http:__smashco.challonge.com_CSUWW106WUD.p
rm ./http:__smashco.challonge.com_CSUWW106WUS.p
rm ./http:__smashco.challonge.com_CSUWW107WUD.p
rm ./http:__smashco.challonge.com_CSUWW107WUS.p
rm ./http:__smashco.challonge.com_CSUWW108WUD.p
rm ./http:__smashco.challonge.com_CSUWW108WUS.p
rm ./http:__smashco.challonge.com_CSUWW109WUD.p
rm ./http:__smashco.challonge.com_CSUWW109WUS.p
rm ./http:__smashco.challonge.com_CSUWW10WUD.p
rm ./http:__smashco.challonge.com_CSUWW10WUS.p
rm ./http:__smashco.challonge.com_CSUWW110WUD.p
rm ./http:__smashco.challonge.com_CSUWW110WUS.p
rm ./http:__smashco.challonge.com_CSUWW111WUD.p
rm ./http:__smashco.challonge.com_CSUWW111WUS.p
rm ./http:__smashco.challonge.com_CSUWW112WUD.p
rm ./http:__smashco.challonge.com_CSUWW112WUS.p
rm ./http:__smashco.challonge.com_CSUWW113WUD.p
rm ./http:__smashco.challonge.com_CSUWW113WUS.p
rm ./http:__smashco.challonge.com_CSUWW114WUD.p
rm ./http:__smashco.challonge.com_CSUWW114WUS.p
rm ./http:__smashco.challonge.com_CSUWW115WUD.p
rm ./http:__smashco.challonge.com_CSUWW115WUS.p
rm ./http:__smashco.challonge.com_CSUWW116WUD.p
rm ./http:__smashco.challonge.com_CSUWW116WUS.p
rm ./http:__smashco.challonge.com_CSUWW117WUD.p
rm ./http:__smashco.challonge.com_CSUWW117WUS.p
rm ./http:__smashco.challonge.com_CSUWW118WUD.p
rm ./http:__smashco.challonge.com_CSUWW118WUS.p
rm ./http:__smashco.challonge.com_CSUWW119WUD.p
rm ./http:__smashco.challonge.com_CSUWW119WUS.p
rm ./http:__smashco.challonge.com_CSUWW11WUD.p
rm ./http:__smashco.challonge.com_CSUWW11WUS.p
rm ./http:__smashco.challonge.com_CSUWW120WUD.p
rm ./http:__smashco.challonge.com_CSUWW120WUS.p
rm ./http:__smashco.challonge.com_CSUWW121WUD.p
rm ./http:__smashco.challonge.com_CSUWW121WUS.p
rm ./http:__smashco.challonge.com_CSUWW122WUD.p
rm ./http:__smashco.challonge.com_CSUWW122WUS.p
rm ./http:__smashco.challonge.com_CSUWW123WUD.p
rm ./http:__smashco.challonge.com_CSUWW123WUS.p
rm ./http:__smashco.challonge.com_CSUWW124WUD.p
rm ./http:__smashco.challonge.com_CSUWW124WUS.p
rm ./http:__smashco.challonge.com_CSUWW125WUD.p
rm ./http:__smashco.challonge.com_CSUWW125WUS.p
rm ./http:__smashco.challonge.com_CSUWW12WUD.p
rm ./http:__smashco.challonge.com_CSUWW12WUS.p
rm ./http:__smashco.challonge.com_CSUWW13WUD.p
rm ./http:__smashco.challonge.com_CSUWW13WUS.p
rm ./http:__smashco.challonge.com_CSUWW14WUD.p
rm ./http:__smashco.challonge.com_CSUWW14WUS.p
rm ./http:__smashco.challonge.com_CSUWW15WUD.p
rm ./http:__smashco.challonge.com_CSUWW15WUS.p
rm ./http:__smashco.challonge.com_CSUWW16WUD.p
rm ./http:__smashco.challonge.com_CSUWW16WUS.p
rm ./http:__smashco.challonge.com_CSUWW17WUD.p
rm ./http:__smashco.challonge.com_CSUWW17WUS.p
rm ./http:__smashco.challonge.com_CSUWW18WUD.p
rm ./http:__smashco.challonge.com_CSUWW18WUS.p
rm ./http:__smashco.challonge.com_CSUWW19WUD.p
rm ./http:__smashco.challonge.com_CSUWW19WUS.p
rm ./http:__smashco.challonge.com_CSUWW1WUD.p
rm ./http:__smashco.challonge.com_CSUWW1WUS.p
rm ./http:__smashco.challonge.com_CSUWW20WUD.p
rm ./http:__smashco.challonge.com_CSUWW20WUS.p
rm ./http:__smashco.challonge.com_CSUWW21WUD.p
rm ./http:__smashco.challonge.com_CSUWW21WUS.p
rm ./http:__smashco.challonge.com_CSUWW22WUD.p
rm ./http:__smashco.challonge.com_CSUWW22WUS.p
rm ./http:__smashco.challonge.com_CSUWW23WUD.p
rm ./http:__smashco.challonge.com_CSUWW23WUS.p
rm ./http:__smashco.challonge.com_CSUWW24WUD.p
rm ./http:__smashco.challonge.com_CSUWW24WUS.p
rm ./http:__smashco.challonge.com_CSUWW25WUD.p
rm ./http:__smashco.challonge.com_CSUWW25WUS.p
rm ./http:__smashco.challonge.com_CSUWW26WUD.p
rm ./http:__smashco.challonge.com_CSUWW26WUS.p
rm ./http:__smashco.challonge.com_CSUWW27WUD.p
rm ./http:__smashco.challonge.com_CSUWW27WUS.p
rm ./http:__smashco.challonge.com_CSUWW28WUD.p
rm ./http:__smashco.challonge.com_CSUWW28WUS.p
rm ./http:__smashco.challonge.com_CSUWW29WUD.p
rm ./http:__smashco.challonge.com_CSUWW29WUS.p
rm ./http:__smashco.challonge.com_CSUWW2WUD.p
rm ./http:__smashco.challonge.com_CSUWW2WUS.p
rm ./http:__smashco.challonge.com_CSUWW30WUD.p
rm ./http:__smashco.challonge.com_CSUWW30WUS.p
rm ./http:__smashco.challonge.com_CSUWW31WUD.p
rm ./http:__smashco.challonge.com_CSUWW31WUS.p
rm ./http:__smashco.challonge.com_CSUWW32WUD.p
rm ./http:__smashco.challonge.com_CSUWW32WUS.p
rm ./http:__smashco.challonge.com_CSUWW33WUD.p
rm ./http:__smashco.challonge.com_CSUWW33WUS.p
rm ./http:__smashco.challonge.com_CSUWW34WUD.p
rm ./http:__smashco.challonge.com_CSUWW34WUS.p
rm ./http:__smashco.challonge.com_CSUWW35WUD.p
rm ./http:__smashco.challonge.com_CSUWW35WUS.p
rm ./http:__smashco.challonge.com_CSUWW36WUD.p
rm ./http:__smashco.challonge.com_CSUWW36WUS.p
rm ./http:__smashco.challonge.com_CSUWW37WUD.p
rm ./http:__smashco.challonge.com_CSUWW37WUS.p
rm ./http:__smashco.challonge.com_CSUWW38WUD.p
rm ./http:__smashco.challonge.com_CSUWW38WUS.p
rm ./http:__smashco.challonge.com_CSUWW39WUD.p
rm ./http:__smashco.challonge.com_CSUWW39WUS.p
rm ./http:__smashco.challonge.com_CSUWW3WUD.p
rm ./http:__smashco.challonge.com_CSUWW3WUS.p
rm ./http:__smashco.challonge.com_CSUWW40WUD.p
rm ./http:__smashco.challonge.com_CSUWW40WUS.p
rm ./http:__smashco.challonge.com_CSUWW41WUD.p
rm ./http:__smashco.challonge.com_CSUWW41WUS.p
rm ./http:__smashco.challonge.com_CSUWW42WUD.p
rm ./http:__smashco.challonge.com_CSUWW42WUS.p
rm ./http:__smashco.challonge.com_CSUWW43WUD.p
rm ./http:__smashco.challonge.com_CSUWW43WUS.p
rm ./http:__smashco.challonge.com_CSUWW44WUD.p
rm ./http:__smashco.challonge.com_CSUWW44WUS.p
rm ./http:__smashco.challonge.com_CSUWW45WUD.p
rm ./http:__smashco.challonge.com_CSUWW45WUS.p
rm ./http:__smashco.challonge.com_CSUWW46WUD.p
rm ./http:__smashco.challonge.com_CSUWW46WUS.p
rm ./http:__smashco.challonge.com_CSUWW47WUD.p
rm ./http:__smashco.challonge.com_CSUWW47WUS.p
rm ./http:__smashco.challonge.com_CSUWW48WUD.p
rm ./http:__smashco.challonge.com_CSUWW48WUS.p
rm ./http:__smashco.challonge.com_CSUWW49WUD.p
rm ./http:__smashco.challonge.com_CSUWW49WUS.p
rm ./http:__smashco.challonge.com_CSUWW4WUD.p
rm ./http:__smashco.challonge.com_CSUWW4WUS.p
rm ./http:__smashco.challonge.com_CSUWW50WUD.p
rm ./http:__smashco.challonge.com_CSUWW50WUS.p
rm ./http:__smashco.challonge.com_CSUWW51WUD.p
rm ./http:__smashco.challonge.com_CSUWW51WUS.p
rm ./http:__smashco.challonge.com_CSUWW52WUD.p
rm ./http:__smashco.challonge.com_CSUWW52WUS.p
rm ./http:__smashco.challonge.com_CSUWW53WUD.p
rm ./http:__smashco.challonge.com_CSUWW53WUS.p
rm ./http:__smashco.challonge.com_CSUWW54WUD.p
rm ./http:__smashco.challonge.com_CSUWW54WUS.p
rm ./http:__smashco.challonge.com_CSUWW55WUD.p
rm ./http:__smashco.challonge.com_CSUWW55WUS.p
rm ./http:__smashco.challonge.com_CSUWW56WUD.p
rm ./http:__smashco.challonge.com_CSUWW56WUS.p
rm ./http:__smashco.challonge.com_CSUWW57WUD.p
rm ./http:__smashco.challonge.com_CSUWW57WUS.p
rm ./http:__smashco.challonge.com_CSUWW58WUD.p
rm ./http:__smashco.challonge.com_CSUWW58WUS.p
rm ./http:__smashco.challonge.com_CSUWW59WUD.p
rm ./http:__smashco.challonge.com_CSUWW59WUS.p
rm ./http:__smashco.challonge.com_CSUWW5WUD.p
rm ./http:__smashco.challonge.com_CSUWW5WUS.p
rm ./http:__smashco.challonge.com_CSUWW60WUD.p
rm ./http:__smashco.challonge.com_CSUWW60WUS.p
rm ./http:__smashco.challonge.com_CSUWW61WUD.p
rm ./http:__smashco.challonge.com_CSUWW61WUS.p
rm ./http:__smashco.challonge.com_CSUWW62WUD.p
rm ./http:__smashco.challonge.com_CSUWW62WUS.p
rm ./http:__smashco.challonge.com_CSUWW63WUD.p
rm ./http:__smashco.challonge.com_CSUWW63WUS.p
rm ./http:__smashco.challonge.com_CSUWW64WUD.p
rm ./http:__smashco.challonge.com_CSUWW64WUS.p
rm ./http:__smashco.challonge.com_CSUWW65WUD.p
rm ./http:__smashco.challonge.com_CSUWW65WUS.p
rm ./http:__smashco.challonge.com_CSUWW66WUD.p
rm ./http:__smashco.challonge.com_CSUWW66WUS.p
rm ./http:__smashco.challonge.com_CSUWW67WUD.p
rm ./http:__smashco.challonge.com_CSUWW67WUS.p
rm ./http:__smashco.challonge.com_CSUWW68WUD.p
rm ./http:__smashco.challonge.com_CSUWW68WUS.p
rm ./http:__smashco.challonge.com_CSUWW69WUD.p
rm ./http:__smashco.challonge.com_CSUWW69WUS.p
rm ./http:__smashco.challonge.com_CSUWW6WUD.p
rm ./http:__smashco.challonge.com_CSUWW6WUS.p
rm ./http:__smashco.challonge.com_CSUWW70WUD.p
rm ./http:__smashco.challonge.com_CSUWW70WUS.p
rm ./http:__smashco.challonge.com_CSUWW71WUD.p
rm ./http:__smashco.challonge.com_CSUWW71WUS.p
rm ./http:__smashco.challonge.com_CSUWW72WUD.p
rm ./http:__smashco.challonge.com_CSUWW72WUS.p
rm ./http:__smashco.challonge.com_CSUWW73WUD.p
rm ./http:__smashco.challonge.com_CSUWW73WUS.p
rm ./http:__smashco.challonge.com_CSUWW74WUD.p
rm ./http:__smashco.challonge.com_CSUWW74WUS.p
rm ./http:__smashco.challonge.com_CSUWW75WUD.p
rm ./http:__smashco.challonge.com_CSUWW75WUS.p
rm ./http:__smashco.challonge.com_CSUWW76WUD.p
rm ./http:__smashco.challonge.com_CSUWW76WUS.p
rm ./http:__smashco.challonge.com_CSUWW77WUD.p
rm ./http:__smashco.challonge.com_CSUWW77WUS.p
rm ./http:__smashco.challonge.com_CSUWW78WUD.p
rm ./http:__smashco.challonge.com_CSUWW78WUS.p
rm ./http:__smashco.challonge.com_CSUWW79WUD.p
rm ./http:__smashco.challonge.com_CSUWW79WUS.p
rm ./http:__smashco.challonge.com_CSUWW7WUD.p
rm ./http:__smashco.challonge.com_CSUWW7WUS.p
rm ./http:__smashco.challonge.com_CSUWW80WUD.p
rm ./http:__smashco.challonge.com_CSUWW80WUS.p
rm ./http:__smashco.challonge.com_CSUWW81WUD.p
rm ./http:__smashco.challonge.com_CSUWW81WUS.p
rm ./http:__smashco.challonge.com_CSUWW82WUD.p
rm ./http:__smashco.challonge.com_CSUWW82WUS.p
rm ./http:__smashco.challonge.com_CSUWW83WUD.p
rm ./http:__smashco.challonge.com_CSUWW83WUS.p
rm ./http:__smashco.challonge.com_CSUWW84WUD.p
rm ./http:__smashco.challonge.com_CSUWW84WUS.p
rm ./http:__smashco.challonge.com_CSUWW85WUD.p
rm ./http:__smashco.challonge.com_CSUWW85WUS.p
rm ./http:__smashco.challonge.com_CSUWW86WUD.p
rm ./http:__smashco.challonge.com_CSUWW86WUS.p
rm ./http:__smashco.challonge.com_CSUWW87WUD.p
rm ./http:__smashco.challonge.com_CSUWW87WUS.p
rm ./http:__smashco.challonge.com_CSUWW88WUD.p
rm ./http:__smashco.challonge.com_CSUWW88WUS.p
rm ./http:__smashco.challonge.com_CSUWW89WUD.p
rm ./http:__smashco.challonge.com_CSUWW89WUS.p
rm ./http:__smashco.challonge.com_CSUWW8WUD.p
rm ./http:__smashco.challonge.com_CSUWW8WUS.p
rm ./http:__smashco.challonge.com_CSUWW90WUD.p
rm ./http:__smashco.challonge.com_CSUWW90WUS.p
rm ./http:__smashco.challonge.com_CSUWW91WUD.p
rm ./http:__smashco.challonge.com_CSUWW91WUS.p
rm ./http:__smashco.challonge.com_CSUWW92WUD.p
rm ./http:__smashco.challonge.com_CSUWW92WUS.p
rm ./http:__smashco.challonge.com_CSUWW93WUD.p
rm ./http:__smashco.challonge.com_CSUWW93WUS.p
rm ./http:__smashco.challonge.com_CSUWW94WUD.p
rm ./http:__smashco.challonge.com_CSUWW94WUS.p
rm ./http:__smashco.challonge.com_CSUWW95WUD.p
rm ./http:__smashco.challonge.com_CSUWW95WUS.p
rm ./http:__smashco.challonge.com_CSUWW96WUD.p
rm ./http:__smashco.challonge.com_CSUWW96WUS.p
rm ./http:__smashco.challonge.com_CSUWW97WUD.p
rm ./http:__smashco.challonge.com_CSUWW97WUS.p
rm ./http:__smashco.challonge.com_CSUWW98WUD.p
rm ./http:__smashco.challonge.com_CSUWW98WUS.p
rm ./http:__smashco.challonge.com_CSUWW99WUD.p
rm ./http:__smashco.challonge.com_CSUWW99WUS.p
rm ./http:__smashco.challonge.com_CSUWW9WUD.p
rm ./http:__smashco.challonge.com_CSUWW9WUS.p
rm ./http:__smashco.challonge.com_FCWUDC1.p
rm ./http:__smashco.challonge.com_FCWUDC10.p
rm ./http:__smashco.challonge.com_FCWUDC11.p
rm ./http:__smashco.challonge.com_FCWUDC12.p
rm ./http:__smashco.challonge.com_FCWUDC13.p
rm ./http:__smashco.challonge.com_FCWUDC14.p
rm ./http:__smashco.challonge.com_FCWUDC15.p
rm ./http:__smashco.challonge.com_FCWUDC16.p
rm ./http:__smashco.challonge.com_FCWUDC17.p
rm ./http:__smashco.challonge.com_FCWUDC18.p
rm ./http:__smashco.challonge.com_FCWUDC19.p
rm ./http:__smashco.challonge.com_FCWUDC2.p
rm ./http:__smashco.challonge.com_FCWUDC20.p
rm ./http:__smashco.challonge.com_FCWUDC21.p
rm ./http:__smashco.challonge.com_FCWUDC22.p
rm ./http:__smashco.challonge.com_FCWUDC23.p
rm ./http:__smashco.challonge.com_FCWUDC24.p
rm ./http:__smashco.challonge.com_FCWUDC25.p
rm ./http:__smashco.challonge.com_FCWUDC26.p
rm ./http:__smashco.challonge.com_FCWUDC27.p
rm ./http:__smashco.challonge.com_FCWUDC28.p
rm ./http:__smashco.challonge.com_FCWUDC29.p
rm ./http:__smashco.challonge.com_FCWUDC3.p
rm ./http:__smashco.challonge.com_FCWUDC30.p
rm ./http:__smashco.challonge.com_FCWUDC31.p
rm ./http:__smashco.challonge.com_FCWUDC32.p
rm ./http:__smashco.challonge.com_FCWUDC33.p
rm ./http:__smashco.challonge.com_FCWUDC34.p
rm ./http:__smashco.challonge.com_FCWUDC35.p
rm ./http:__smashco.challonge.com_FCWUDC36.p
rm ./http:__smashco.challonge.com_FCWUDC37.p
rm ./http:__smashco.challonge.com_FCWUDC38.p
rm ./http:__smashco.challonge.com_FCWUDC39.p
rm ./http:__smashco.challonge.com_FCWUDC4.p
rm ./http:__smashco.challonge.com_FCWUDC40.p
rm ./http:__smashco.challonge.com_FCWUDC41.p
rm ./http:__smashco.challonge.com_FCWUDC42.p
rm ./http:__smashco.challonge.com_FCWUDC43.p
rm ./http:__smashco.challonge.com_FCWUDC44.p
rm ./http:__smashco.challonge.com_FCWUDC45.p
rm ./http:__smashco.challonge.com_FCWUDC46.p
rm ./http:__smashco.challonge.com_FCWUDC47.p
rm ./http:__smashco.challonge.com_FCWUDC48.p
rm ./http:__smashco.challonge.com_FCWUDC49.p
rm ./http:__smashco.challonge.com_FCWUDC5.p
rm ./http:__smashco.challonge.com_FCWUDC50.p
rm ./http:__smashco.challonge.com_FCWUDC51.p
rm ./http:__smashco.challonge.com_FCWUDC52.p
rm ./http:__smashco.challonge.com_FCWUDC53.p
rm ./http:__smashco.challonge.com_FCWUDC54.p
rm ./http:__smashco.challonge.com_FCWUDC55.p
rm ./http:__smashco.challonge.com_FCWUDC6.p
rm ./http:__smashco.challonge.com_FCWUDC7.p
rm ./http:__smashco.challonge.com_FCWUDC8.p
rm ./http:__smashco.challonge.com_FCWUDC9.p
rm ./https:__austinsmash4.challonge.com_atx1.p
rm ./https:__austinsmash4.challonge.com_atx10.p
rm ./https:__austinsmash4.challonge.com_atx103.p
rm ./https:__austinsmash4.challonge.com_atx104.p
rm ./https:__austinsmash4.challonge.com_atx105.p
rm ./https:__austinsmash4.challonge.com_atx108.p
rm ./https:__austinsmash4.challonge.com_atx109.p
rm ./https:__austinsmash4.challonge.com_atx11.p
rm ./https:__austinsmash4.challonge.com_atx110.p
rm ./https:__austinsmash4.challonge.com_atx111.p
rm ./https:__austinsmash4.challonge.com_atx112.p
rm ./https:__austinsmash4.challonge.com_atx113.p
rm ./https:__austinsmash4.challonge.com_atx115.p
rm ./https:__austinsmash4.challonge.com_atx116.p
rm ./https:__austinsmash4.challonge.com_atx116_standings.p
rm ./https:__austinsmash4.challonge.com_atx117.p
rm ./https:__austinsmash4.challonge.com_atx117_standings.p
rm ./https:__austinsmash4.challonge.com_atx119.p
rm ./https:__austinsmash4.challonge.com_atx119_standings.p
rm ./https:__austinsmash4.challonge.com_atx12.p
rm ./https:__austinsmash4.challonge.com_atx120.p
rm ./https:__austinsmash4.challonge.com_atx120_standings.p
rm ./https:__austinsmash4.challonge.com_atx121.p
rm ./https:__austinsmash4.challonge.com_atx121_standings.p
rm ./https:__austinsmash4.challonge.com_atx123.p
rm ./https:__austinsmash4.challonge.com_atx128.p
rm ./https:__austinsmash4.challonge.com_atx129.p
rm ./https:__austinsmash4.challonge.com_atx13.p
rm ./https:__austinsmash4.challonge.com_atx130.p
rm ./https:__austinsmash4.challonge.com_atx132.p
rm ./https:__austinsmash4.challonge.com_atx135.p
rm ./https:__austinsmash4.challonge.com_atx14.p
rm ./https:__austinsmash4.challonge.com_atx140.p
rm ./https:__austinsmash4.challonge.com_atx141.p
rm ./https:__austinsmash4.challonge.com_atx146.p
rm ./https:__austinsmash4.challonge.com_atx146_standings.p
rm ./https:__austinsmash4.challonge.com_atx147.p
rm ./https:__austinsmash4.challonge.com_atx148.p
rm ./https:__austinsmash4.challonge.com_atx149.p
rm ./https:__austinsmash4.challonge.com_atx149_standings.p
rm ./https:__austinsmash4.challonge.com_atx15.p
rm ./https:__austinsmash4.challonge.com_atx151.p
rm ./https:__austinsmash4.challonge.com_atx152.p
rm ./https:__austinsmash4.challonge.com_atx153.p
rm ./https:__austinsmash4.challonge.com_atx154.p
rm ./https:__austinsmash4.challonge.com_atx155.p
rm ./https:__austinsmash4.challonge.com_atx156.p
rm ./https:__austinsmash4.challonge.com_atx157.p
rm ./https:__austinsmash4.challonge.com_atx158.p
rm ./https:__austinsmash4.challonge.com_atx159.p
rm ./https:__austinsmash4.challonge.com_atx16.p
rm ./https:__austinsmash4.challonge.com_atx160.p
rm ./https:__austinsmash4.challonge.com_atx161.p
rm ./https:__austinsmash4.challonge.com_atx162.p
rm ./https:__austinsmash4.challonge.com_atx163.p
rm ./https:__austinsmash4.challonge.com_atx164.p
rm ./https:__austinsmash4.challonge.com_atx165.p
rm ./https:__austinsmash4.challonge.com_atx166.p
rm ./https:__austinsmash4.challonge.com_atx167.p
rm ./https:__austinsmash4.challonge.com_atx168.p
rm ./https:__austinsmash4.challonge.com_atx169.p
rm ./https:__austinsmash4.challonge.com_atx17.p
rm ./https:__austinsmash4.challonge.com_atx170.p
rm ./https:__austinsmash4.challonge.com_atx171.p
rm ./https:__austinsmash4.challonge.com_atx172.p
rm ./https:__austinsmash4.challonge.com_atx173.p
rm ./https:__austinsmash4.challonge.com_atx174.p
rm ./https:__austinsmash4.challonge.com_atx175.p
rm ./https:__austinsmash4.challonge.com_atx176.p
rm ./https:__austinsmash4.challonge.com_atx177.p
rm ./https:__austinsmash4.challonge.com_atx178.p
rm ./https:__austinsmash4.challonge.com_atx179.p
rm ./https:__austinsmash4.challonge.com_atx18.p
rm ./https:__austinsmash4.challonge.com_atx180.p
rm ./https:__austinsmash4.challonge.com_atx181.p
rm ./https:__austinsmash4.challonge.com_atx182.p
rm ./https:__austinsmash4.challonge.com_atx183.p
rm ./https:__austinsmash4.challonge.com_atx184.p
rm ./https:__austinsmash4.challonge.com_atx185.p
rm ./https:__austinsmash4.challonge.com_atx186.p
rm ./https:__austinsmash4.challonge.com_atx187.p
rm ./https:__austinsmash4.challonge.com_atx188.p
rm ./https:__austinsmash4.challonge.com_atx189.p
rm ./https:__austinsmash4.challonge.com_atx19.p
rm ./https:__austinsmash4.challonge.com_atx190.p
rm ./https:__austinsmash4.challonge.com_atx191.p
rm ./https:__austinsmash4.challonge.com_atx192.p
rm ./https:__austinsmash4.challonge.com_atx193.p
rm ./https:__austinsmash4.challonge.com_atx194.p
rm ./https:__austinsmash4.challonge.com_atx195.p
rm ./https:__austinsmash4.challonge.com_atx196.p
rm ./https:__austinsmash4.challonge.com_atx197.p
rm ./https:__austinsmash4.challonge.com_atx198.p
rm ./https:__austinsmash4.challonge.com_atx199.p
rm ./https:__austinsmash4.challonge.com_atx2.p
rm ./https:__austinsmash4.challonge.com_atx20.p
rm ./https:__austinsmash4.challonge.com_atx200.p
rm ./https:__austinsmash4.challonge.com_atx201.p
rm ./https:__austinsmash4.challonge.com_atx21.p
rm ./https:__austinsmash4.challonge.com_atx22.p
rm ./https:__austinsmash4.challonge.com_atx23.p
rm ./https:__austinsmash4.challonge.com_atx24.p
rm ./https:__austinsmash4.challonge.com_atx25.p
rm ./https:__austinsmash4.challonge.com_atx26.p
rm ./https:__austinsmash4.challonge.com_atx27.p
rm ./https:__austinsmash4.challonge.com_atx28.p
rm ./https:__austinsmash4.challonge.com_atx29.p
rm ./https:__austinsmash4.challonge.com_atx3.p
rm ./https:__austinsmash4.challonge.com_atx30.p
rm ./https:__austinsmash4.challonge.com_atx31.p
rm ./https:__austinsmash4.challonge.com_atx32.p
rm ./https:__austinsmash4.challonge.com_atx33.p
rm ./https:__austinsmash4.challonge.com_atx34.p
rm ./https:__austinsmash4.challonge.com_atx35.p
rm ./https:__austinsmash4.challonge.com_atx36.p
rm ./https:__austinsmash4.challonge.com_atx37.p
rm ./https:__austinsmash4.challonge.com_atx38.p
rm ./https:__austinsmash4.challonge.com_atx39.p
rm ./https:__austinsmash4.challonge.com_atx4.p
rm ./https:__austinsmash4.challonge.com_atx40.p
rm ./https:__austinsmash4.challonge.com_atx41.p
rm ./https:__austinsmash4.challonge.com_atx42.p
rm ./https:__austinsmash4.challonge.com_atx43.p
rm ./https:__austinsmash4.challonge.com_atx44.p
rm ./https:__austinsmash4.challonge.com_atx45.p
rm ./https:__austinsmash4.challonge.com_atx46.p
rm ./https:__austinsmash4.challonge.com_atx47.p
rm ./https:__austinsmash4.challonge.com_atx48.p
rm ./https:__austinsmash4.challonge.com_atx49.p
rm ./https:__austinsmash4.challonge.com_atx5.p
rm ./https:__austinsmash4.challonge.com_atx50.p
rm ./https:__austinsmash4.challonge.com_atx51.p
rm ./https:__austinsmash4.challonge.com_atx52.p
rm ./https:__austinsmash4.challonge.com_atx53.p
rm ./https:__austinsmash4.challonge.com_atx54.p
rm ./https:__austinsmash4.challonge.com_atx55.p
rm ./https:__austinsmash4.challonge.com_atx56.p
rm ./https:__austinsmash4.challonge.com_atx57.p
rm ./https:__austinsmash4.challonge.com_atx58.p
rm ./https:__austinsmash4.challonge.com_atx59.p
rm ./https:__austinsmash4.challonge.com_atx6.p
rm ./https:__austinsmash4.challonge.com_atx60.p
rm ./https:__austinsmash4.challonge.com_atx61.p
rm ./https:__austinsmash4.challonge.com_atx62.p
rm ./https:__austinsmash4.challonge.com_atx63.p
rm ./https:__austinsmash4.challonge.com_atx64.p
rm ./https:__austinsmash4.challonge.com_atx65.p
rm ./https:__austinsmash4.challonge.com_atx66.p
rm ./https:__austinsmash4.challonge.com_atx67.p
rm ./https:__austinsmash4.challonge.com_atx67_standings.p
rm ./https:__austinsmash4.challonge.com_atx69.p
rm ./https:__austinsmash4.challonge.com_atx7.p
rm ./https:__austinsmash4.challonge.com_atx70.p
rm ./https:__austinsmash4.challonge.com_atx71.p
rm ./https:__austinsmash4.challonge.com_atx71_standings.p
rm ./https:__austinsmash4.challonge.com_atx72.p
rm ./https:__austinsmash4.challonge.com_atx73.p
rm ./https:__austinsmash4.challonge.com_atx74.p
rm ./https:__austinsmash4.challonge.com_atx76.p
rm ./https:__austinsmash4.challonge.com_atx78.p
rm ./https:__austinsmash4.challonge.com_atx79.p
rm ./https:__austinsmash4.challonge.com_atx8.p
rm ./https:__austinsmash4.challonge.com_atx80.p
rm ./https:__austinsmash4.challonge.com_atx81.p
rm ./https:__austinsmash4.challonge.com_atx82.p
rm ./https:__austinsmash4.challonge.com_atx83.p
rm ./https:__austinsmash4.challonge.com_atx87.p
rm ./https:__austinsmash4.challonge.com_atx88.p
rm ./https:__austinsmash4.challonge.com_atx9.p
rm ./https:__austinsmash4.challonge.com_atx91.p
rm ./https:__austinsmash4.challonge.com_atx92.p
rm ./https:__austinsmash4.challonge.com_atx93.p
rm ./https:__austinsmash4.challonge.com_atx94.p
rm ./https:__austinsmash4.challonge.com_atx95.p
rm ./https:__austinsmash4.challonge.com_atx97.p
rm ./https:__austinsmash4.challonge.com_atx98.p
rm ./https:__austinsmash4.challonge.com_atx99.p
rm ./https:__challonge.com_NP9ATX10.p
rm ./https:__challonge.com_NP9ATX12.p
rm ./https:__challonge.com_NP9ATX14.p
rm ./https:__challonge.com_NP9ATX17.p
rm ./https:__challonge.com_NP9ATX18.p
rm ./https:__challonge.com_NP9ATX2.p
rm ./https:__challonge.com_NP9ATX23.p
rm ./https:__challonge.com_NP9ATX26.p
rm ./https:__challonge.com_NP9ATX26_standings.p
rm ./https:__challonge.com_NP9ATX28.p
rm ./https:__challonge.com_NP9ATX29.p
rm ./https:__challonge.com_NP9ATX29_standings.p
rm ./https:__challonge.com_NP9ATX3.p
rm ./https:__challonge.com_NP9ATX30.p
rm ./https:__challonge.com_NP9ATX31.p
rm ./https:__challonge.com_NP9ATX32.p
rm ./https:__challonge.com_NP9ATX33.p
rm ./https:__challonge.com_NP9ATX34.p
rm ./https:__challonge.com_NP9ATX35.p
rm ./https:__challonge.com_NP9ATX36.p
rm ./https:__challonge.com_NP9ATX37.p
rm ./https:__challonge.com_NP9ATX38.p
rm ./https:__challonge.com_NP9ATX39.p
rm ./https:__challonge.com_NP9ATX40.p
rm ./https:__challonge.com_NP9ATX41.p
rm ./https:__challonge.com_NP9ATX42.p
rm ./https:__challonge.com_NP9ATX43.p
rm ./https:__challonge.com_NP9ATX44.p
rm ./https:__challonge.com_NP9ATX45.p
rm ./https:__challonge.com_NP9ATX46.p
rm ./https:__challonge.com_NP9ATX47.p
rm ./https:__challonge.com_NP9ATX48.p
rm ./https:__challonge.com_NP9ATX49.p
rm ./https:__challonge.com_NP9ATX5.p
rm ./https:__challonge.com_NP9ATX50.p
rm ./https:__challonge.com_NP9ATX51.p
rm ./https:__challonge.com_NP9ATX52.p
rm ./https:__challonge.com_NP9ATX53.p
rm ./https:__challonge.com_NP9ATX54.p
rm ./https:__challonge.com_NP9ATX55.p
rm ./https:__challonge.com_NP9ATX56.p
rm ./https:__challonge.com_NP9ATX57.p
rm ./https:__challonge.com_NP9ATX58.p
rm ./https:__challonge.com_NP9ATX59.p
rm ./https:__challonge.com_NP9ATX6.p
rm ./https:__challonge.com_NP9ATX60.p
rm ./https:__challonge.com_NP9ATX61.p
rm ./https:__challonge.com_NP9ATX62.p
rm ./https:__challonge.com_NP9ATX63.p
rm ./https:__challonge.com_NP9ATX64.p
rm ./https:__challonge.com_NP9ATX65.p
rm ./https:__challonge.com_NP9ATX66.p
rm ./https:__challonge.com_NP9ATX67.p
rm ./https:__challonge.com_NP9ATX68.p
rm ./https:__challonge.com_NP9ATX69.p
rm ./https:__challonge.com_NP9ATX7.p
rm ./https:__challonge.com_NP9ATX70.p
rm ./https:__challonge.com_NP9ATX71.p
rm ./https:__challonge.com_NP9ATX72.p
rm ./https:__challonge.com_NP9ATX73.p
rm ./https:__challonge.com_NP9ATX74.p
rm ./https:__challonge.com_NP9ATX75.p
rm ./https:__challonge.com_NP9ATX76.p
rm ./https:__challonge.com_NP9ATX77.p
rm ./https:__challonge.com_NP9ATX78.p
rm ./https:__challonge.com_NP9ATX79.p
rm ./https:__challonge.com_NP9ATX8.p
rm ./https:__challonge.com_NP9ATX80.p
rm ./https:__challonge.com_NP9ATX81.p
rm ./https:__challonge.com_NP9ATX82.p
rm ./https:__challonge.com_NP9ATX83.p
rm ./https:__challonge.com_Smashbrews1.p
rm ./https:__challonge.com_Smashbrews10.p
rm ./https:__challonge.com_Smashbrews100.p
rm ./https:__challonge.com_Smashbrews101.p
rm ./https:__challonge.com_Smashbrews102.p
rm ./https:__challonge.com_Smashbrews103.p
rm ./https:__challonge.com_Smashbrews104.p
rm ./https:__challonge.com_Smashbrews105.p
rm ./https:__challonge.com_Smashbrews106.p
rm ./https:__challonge.com_Smashbrews107.p
rm ./https:__challonge.com_Smashbrews108.p
rm ./https:__challonge.com_Smashbrews109.p
rm ./https:__challonge.com_Smashbrews11.p
rm ./https:__challonge.com_Smashbrews110.p
rm ./https:__challonge.com_Smashbrews111.p
rm ./https:__challonge.com_Smashbrews112.p
rm ./https:__challonge.com_Smashbrews113.p
rm ./https:__challonge.com_Smashbrews114.p
rm ./https:__challonge.com_Smashbrews115.p
rm ./https:__challonge.com_Smashbrews116.p
rm ./https:__challonge.com_Smashbrews117.p
rm ./https:__challonge.com_Smashbrews118.p
rm ./https:__challonge.com_Smashbrews119.p
rm ./https:__challonge.com_Smashbrews12.p
rm ./https:__challonge.com_Smashbrews120.p
rm ./https:__challonge.com_Smashbrews121.p
rm ./https:__challonge.com_Smashbrews122.p
rm ./https:__challonge.com_Smashbrews13.p
rm ./https:__challonge.com_Smashbrews14.p
rm ./https:__challonge.com_Smashbrews15.p
rm ./https:__challonge.com_Smashbrews16.p
rm ./https:__challonge.com_Smashbrews17.p
rm ./https:__challonge.com_Smashbrews18.p
rm ./https:__challonge.com_Smashbrews19.p
rm ./https:__challonge.com_Smashbrews20.p
rm ./https:__challonge.com_Smashbrews21.p
rm ./https:__challonge.com_Smashbrews22.p
rm ./https:__challonge.com_Smashbrews25.p
rm ./https:__challonge.com_Smashbrews26.p
rm ./https:__challonge.com_Smashbrews27.p
rm ./https:__challonge.com_Smashbrews28.p
rm ./https:__challonge.com_Smashbrews29.p
rm ./https:__challonge.com_Smashbrews3.p
rm ./https:__challonge.com_Smashbrews31.p
rm ./https:__challonge.com_Smashbrews32.p
rm ./https:__challonge.com_Smashbrews4.p
rm ./https:__challonge.com_Smashbrews47.p
rm ./https:__challonge.com_Smashbrews5.p
rm ./https:__challonge.com_Smashbrews50.p
rm ./https:__challonge.com_Smashbrews54.p
rm ./https:__challonge.com_Smashbrews55.p
rm ./https:__challonge.com_Smashbrews6.p
rm ./https:__challonge.com_Smashbrews60.p
rm ./https:__challonge.com_Smashbrews61.p
rm ./https:__challonge.com_Smashbrews63.p
rm ./https:__challonge.com_Smashbrews64.p
rm ./https:__challonge.com_Smashbrews65.p
rm ./https:__challonge.com_Smashbrews66.p
rm ./https:__challonge.com_Smashbrews67.p
rm ./https:__challonge.com_Smashbrews68.p
rm ./https:__challonge.com_Smashbrews70.p
rm ./https:__challonge.com_Smashbrews72.p
rm ./https:__challonge.com_Smashbrews73.p
rm ./https:__challonge.com_Smashbrews74.p
rm ./https:__challonge.com_Smashbrews75.p
rm ./https:__challonge.com_Smashbrews76.p
rm ./https:__challonge.com_Smashbrews77.p
rm ./https:__challonge.com_Smashbrews78.p
rm ./https:__challonge.com_Smashbrews79.p
rm ./https:__challonge.com_Smashbrews8.p
rm ./https:__challonge.com_Smashbrews80.p
rm ./https:__challonge.com_Smashbrews81.p
rm ./https:__challonge.com_Smashbrews82.p
rm ./https:__challonge.com_Smashbrews83.p
rm ./https:__challonge.com_Smashbrews84.p
rm ./https:__challonge.com_Smashbrews85.p
rm ./https:__challonge.com_Smashbrews86.p
rm ./https:__challonge.com_Smashbrews87.p
rm ./https:__challonge.com_Smashbrews88.p
rm ./https:__challonge.com_Smashbrews89.p
rm ./https:__challonge.com_Smashbrews9.p
rm ./https:__challonge.com_Smashbrews90.p
rm ./https:__challonge.com_Smashbrews91.p
rm ./https:__challonge.com_Smashbrews92.p
rm ./https:__challonge.com_Smashbrews93.p
rm ./https:__challonge.com_Smashbrews94.p
rm ./https:__challonge.com_Smashbrews95.p
rm ./https:__challonge.com_Smashbrews96.p
rm ./https:__challonge.com_Smashbrews97.p
rm ./https:__challonge.com_Smashbrews98.p
rm ./https:__challonge.com_Smashbrews99.p
